trigger: none

pool: vkt-pool

stages:
  - stage: buildProcess
    displayName: BUIL Process
    jobs:
      - job: Build
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'

        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'vkt-pipeline'
            backendAzureRmResourceGroupName: 'tfstaterg'
            backendAzureRmStorageAccountName: 'saccountfstate'
            backendAzureRmContainerName: 'tfstatefilestore'
            backendAzureRmKey: 'infra'

  - stage: terrafornplan
    displayName: terrafrom plan
    jobs:
      - job: terraformplan
        steps:
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Production-env'
            environmentServiceNameAzureRM: 'vkt-pipeline'
        
        - task: TerraformTaskV4@4
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'vkt-pipeline'
            backendAzureRmResourceGroupName: 'tfstaterg'
            backendAzureRmStorageAccountName: 'saccountfstate'
            backendAzureRmContainerName: 'tfstatefilestore'
            backendAzureRmKey: 'infra'